buildkite/buildkite-agent-scaler

lambda/main.go, main.go, scaler/scaler.go, scaler/scaler_test.go, template.yaml
This reimplements ASG scale-in cooldown inside the lambda. It takes two parameters which correspond to the existing ASG parameters in the elastic CI stack.
1. `SCALE_IN_COOLDOWN_PERIOD` is the cooldown time between scale in events. This defaults to the existing 5 minutes.
2. `SCALE_IN_ADJUSTMENT` is the maximum adjustment during scale-in events. Unlike the ASG we may scale in less if we calculate that the desired is closer than the adjustment. This defaults to the existing -1.
This cheats a bit by storing `lastScaleInTime` in a global variable. This means we'll forget about our cooldown during a cold start. This should happen fairly infrequently and just make us a bit aggressive about scaling it; it shouldn't affect correctness.
=> Add scale-in cooldown support

lambda/main.go, scaler/scaler.go
This allows opting out of scale-in for cases where the agent's new disconnect when idle feature is used.
=> Add DISABLE_SCALE_IN param to opt-out of scale in

buildkite/buildkite.go, lambda/main.go, scaler/scaler.go
The Buildkite Agent Metrics API returns a header` Buildkite-Agent-Metrics-Poll-Duration` that indicates the minimum poll duration. This is generally 10s, but under periods of heavy load it can scale up.
This limit is enforced in the cli tool and also in the lambda via global state.
=> Respect poll duration header from agent api

lambda/main.go, main.go, scaler/ssm.go
This allows for the Agent Token to be read from SSM Parameter Store, which means it doesn't need to be passed in plain text via the lambda env.
The ParameterStore key can be set via `BUILDKITE_AGENT_TOKEN_SSM_KEY`.
=> Support reading Agent Token from SSM Parameter Store

lambda/main.go, main.go, scaler/scaler.go, scaler/scaler_test.go
This adds a scale-in and scale-out factor that can be used to speed up or slow down scale outs and ins. 
For instance, setting `SCALE_IN_FACTOR=0.5` will reduce the change applied in each scale in by 50%.  Setting `SCALE_OUT_FACTOR=2.0` will increase each scale out change by 200%.
This is a simpler take on #12.
=> Add a configurable scale factor to scale in/out

buildkite/buildkite.go, lambda/main.go, main.go, scaler/scaler.go, scaler/scaler_test.go
The agent metrics api now includes a metric for `WaitingJobCount` which tracks jobs that are behind a wait step. This allows for pre-emptive scaling so that instances are ready by the time that jobs are scheduled. 
By default `waiting` jobs aren't included, but they can be enabled with `INCLUDE_WAITING=1` in the lambda env.
=> Add scaling to include waiting jobs

README.md
The MIN_SIZE and MAX_SIZE variables are not used by the lambda. These
parameters are queried from the Autoscaling Group rather than the
environment.
=> Correct required environment variables in README

buildkite/buildkite.go, buildkite/buildkite_test.go
`buildkite.Client.GetAgentMetrics()` was not handling HTTP errors, and instead returning an empty `AgentMetrics` struct.
This manifested as an apparent zero-value for all metrics, and an empty `org` field in the log output:
```
2019/11/21 19:38:23 Publishing metric WaitingJobsCount=0 [org=,queue=default]
```
Go's HTTP client says:
> A non-2xx status code doesn't cause an error. 
-- https://golang.org/pkg/net/http/#Client.Do
This PR adds status-checking code, and tests for the happy and sad cases.
=> Handle HTTP errors from metrics API

.buildkite/pipeline.release.yml, .buildkite/pipeline.yml, .buildkite/steps/github-release.sh
The "deploy-legacy" queue is deprecated, and we're slowly moving steps off it.
The agents processing the "deploy" queue are an elastic stack, and the awscli is available. It's likely we'll need to update some IAM roles used by those agents, but we do that elsewhere.
One of the steps also uses the github-release tool, which isn't available on the agents. We can use the deploytools image (via a buildkite plugin) to get it though.
github-release also requires a github API token. On the old agents that was set in an agent hook, but now we need to read it from SSM.
=> run deploy steps on the new "deploy"  queue

.buildkite/pipeline.yml, Makefile
Use Go 1.15 to run tests in CI and to build the lambda binary.
=> Build with golang 1.15, was 1.12

README.md
Document the fact that the agent registration token can be read from AWS Parameter Store or Secrets Manager at runtime, rather than being passed directly in the environment.
=> README: read token from AWS Parameter Store / Secrets Manager

buildkite/buildkite.go
Trivial refactor — I was looking at #23 and hated the way I introduced a local var for the HTTP method. This PR passes the `http.MethodGet` const directly to the request, and then references `http.Request.Method` as source of truth to build an error message.
=> Client.queryMetrics: eliminate unnecessary local var indirection

.buildkite/steps/upload-to-s3.sh, template.yaml
New: af-south-1, ap-east-1. ca-central-1,  eu-south-1, eu-west-3, eu-north-1, me-south-1
Related: https://github.com/buildkite/elastic-ci-stack-for-aws/pull/718
=> Support more regions

scaler/scaler.go, scaler/scaler_test.go
We verified this works on a real pipeline using stack built from this PR.
Closes #34.
=> Avoid scale out over max and scale in under min

scaler/scaler.go
Closes https://github.com/buildkite/buildkite-agent-scaler/issues/34
@yob
=> Ensure capacity does not exceed ASG MaxSize

CHANGELOG.md, version/version.go
Notable changes are #37 and #33.
<kbd>[Preview Changelog](https://github.com/buildkite/buildkite-agent-scaler/blob/v102/CHANGELOG.md#v102-2020-10-19)</kbd>
=> Release v1.0.2

buildkite/buildkite.go, lambda/main.go, main.go, scaler/asg.go, scaler/scaler.go, scaler/scaler_test.go, scaler/scaling_calculator.go
Proposed solution to #39. It's fresh off the keyboard, and I haven't had a chance to set up a test lab to verify it does what I expect in the real world yet.
Implements an (opt-in) alternative scaling calculation using relative numbers. i.e. N _more_ instances requires as opposed to N _total_ instances required.
This should work better in cases where not all agents on an instance are running or accepting jobs. For example, while waiting for (potentially long-running) jobs to complete during a graceful shutdown.
=> Relative scaling calculation

scaler/scaling_calculator.go
This was added in #40 but is causing issues where the stack will scale too aggressively.
There is a race condition between an instance being added to the desired count in the ASG and the buildkite agents being registered while the cloud-init bring up is completed.
One way to handle this might be to add a boot time lifecycle hook, to hold the instance in the ASG `Pending` state until the Buildkite agents are booted and can be reliably counted. However, in the short term I think we need to revert this behaviour and roll out an updated stack for customers incurring undesirable additional cost.
I’ve left the additional refactoring in place from that pull request and have just removed the change in the calculation.
=> Revert agent shortfall scaling

lambda/main.go, main.go, scaler/asg.go, scaler/cloudwatch.go, scaler/scaler.go, scaler/ssm.go
This enables shared config checks in the AWS Session SDK for setups that use `~/.aws/credentials`. See https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html
Note that 508764a makes a change where by a single session is used and passed around vs `session.New()` invoked everywhere. It's remotely possible this could break things where creating a new session each time was providing some durability around failures and dropouts unintentionally. I don't think this is likely, as there are internal retry mechanisms in the single session. In fact, I think that it's likely that establishing lots of new sessions could lead to rate-limiting and latency.
=> Use AWS shared credentials config

Makefile
The production version of these commands live in the [pipeline-sar.yml](https://github.com/buildkite/buildkite-agent-scaler/blob/master/.buildkite/pipeline-sar.yml) file with the real bucket and app names.
=> Remove old Makefile targets for SAR

template.yaml
Adds a new optional `DisableScaleIn` parameter that defaults to `true`, the current value. This allows importing stacks to set this to `false` and enable the scale in behaviour of the scaling lambda.
=> Parameterise DisableScaleIn in the template

lambda/main.go, scaler/asg.go, scaler/scaler.go
Currently, the scale in and out event time is set and stored as a global variable. However, if the service does not run in the same container, the event is always reset to 0 and will scale in and out immediately. This change will set the last scale in and out event based on the autoscaler's activity event, so if the service does not run on the same lambda container, it will keep the state of the last time it scaled in or out.
=> Set last scale in and out event on autoscaler activity

template.yaml
Attempts to deploy a Buildkite elastic-ci stack via a role with permission boundary currently fail.  It looks like the autoscaling application doesn't apply the boundary condition ARN passed to the parent stack.  
These two PRs:
https://github.com/buildkite/buildkite-agent-scaler/pull/62
https://github.com/buildkite/elastic-ci-stack-for-aws/pull/984
address this.
=> Adding permissions boundary

CHANGELOG.md, version/version.go
The CI issue that prevented us from releasing 1.3.0 has now been fixed, so this release should actually get released.
=> Bump version + changelog for v1.3.1

README.md, template.yaml
The changes in #52 introduced a new call to the AutoScaling API and this updates the IAM policy in the CloudFormation template accordingly.
Fixes #68
=> Update IAM policy to allow describing scaling activities

CHANGELOG.md, version/version.go
This PR will release v1.3.2, which fixes an issue with describing scaling activities on ASGs.
=> Bump version + changelog for v1.3.2

template.yaml
This PR adds a Cloudformation parameter to configure the cloudwatch log retention. This is currently hardcoded to 1 day, and we'd like to set this to a higher number like 180 days.
=> Add parameter to configure logs retention

lambda/main.go, main.go, scaler/scaler.go, scaler/scaler_test.go, template.yaml
This will help fleets where instance startup time is slow, by allowing them to configure enough free instances to handle a certain amount of load while new instances spin up.
=> Allow running scaler with a fixed size instance buffer

.buildkite/pipeline.release.yml, .buildkite/pipeline.yml, lambda/main.go, scaler/asg.go, scaler/scaler.go, scaler/scaler_test.go
The pipeline for buildkite-agent-scaler used to run some steps on the "deploy" agents, but it should not anymore and is broken anyway.
This is part of a series of PRs to allow agents with fewer privileges to use OIDC to assume a role to do the same thing, but only for the buildkite/buildkite-agent-scaler pipeline.
This follows a pattern established by @yob and the foundation team that was successful for buildkite/buildkite-agent-metrics and is documented here
This PR is step 4 in that comment.
Also I applied go fmt because it kept geting in the way while I was developing https://github.com/buildkite/buildkite-agent-scaler/pull/81. I'll incorporate it into the pipeline in a latter PR.
=> Use OIDC to assume role to publish lambdas to s3

.buildkite/pipeline-sar.yml, .buildkite/steps/build-lambda.sh, .buildkite/steps/github-release.sh, .buildkite/steps/publish-package.sh, Makefile, template.yaml
This will allow us to deploy changes targeted to address certain customer's issues and ask them to test the change on their infrastructure.
Once we are satisfied the change works, we can merge it back in to the trunk branch.
The process for doing so is to manually start a build for the branch/commit you want to release to the edge repo. For example, for a commit that this branch once pointed to: https://buildkite.com/buildkite-aws-stack/buildkite-agent-scaler-publish/builds/49
=> Allow releasing development versions of buildkite-agent-scaler to the an "edge" serverless repo

.buildkite/pipeline.yml
We're standardising the role names to include organization and pipeline slug
=> Update role ARN

lambda/main.go, scaler/asg.go, template.yaml
This fixes a variety of issues with scaler, the main one being that, when scale in was disabled on the elastic ci stack (which it is by default), the search for the last scale in activity would alway go through the entire history of scaling events. As this is paginated, and stores 6 weeks of activity, many customers were experiencing rate limiting of of their autoscaling API calls. This rendered the elastic ci stack unable to scale out in some cases.
Until @YanivAssaf-at pointed this out, my main attempt at a solution was to impose an arbitrary limit on the pagination of the DescribeAutoScalingActivity API. I still think this could be useful, so I have kept it in.
=> Limit pagination of autoscaling:DescribeScalingActivity

.buildkite/pipeline.yml, .buildkite/steps/test-go-fmt.sh, buildkite/buildkite.go, lambda/main.go, scaler/scaler.go
=> Replace all unnecessary backtick strings with reggo strings

.buildkite/pipeline.release.yml
This is preventing v1.4.0 being released properly:
https://buildkite.com/buildkite/buildkite-agent-scaler/builds/254#0188c3a0-e4ed-4ac0-a804-cf360e6befcf
but I think following the pattern from #82 will fix it up.
=> Assume the OIDC role for release-verison too

template.yaml
This PR is being raised to allow the Event Schedule rate to be configurable via Parameter inputs. 
There is a Default value provided to ensure the change is backwards compatible. 
When there are a large number of BuildKite agent queues combined with other resources such as Cluster Autoscalers the AWS API for `DescribeAutoScalingGroupsInfo` receives a `ThrottlingException`. This has a negative impact on all services that are required to interact with the AWS Autoscaling API. 
This PR will allow for the schedule to be updated as required to ensure throttling exceptions are not triggered. 
If this PR is merged, another PR will need to be raised against the elastic CI stack to allow the parameter to be passed in.
=> Allow the event schedule rate to be configured via parameters

template.yaml
This controls the sleep between polls. While it could be set to almost any duration, anything smaller than 10s is overridden by Buildkite-Agent-Metrics-Poll-Duration. 
Fixes #71
=> Add MinPollInterval param

lambda/main.go
And use `context.WithTimeout` technology instead of separate-goroutine-channel-wait technology.
And move the client and scaler creation outside the loop.
Plus minor cleanups with `mustGetEnv{,Int}`.
=> DescribeScalingActivities once

buildkite/buildkite.go
Previously, we polled the index route, which returns the metrics grouped
by queue, and then dropped the metrics for the other queues. This is
wasteful. There is a route scoped to the queue,
```
http 'agent.buildkite.localhost/v3/metrics/queue?name=default' "Authorization: Token **********"
```
it returns the JSON in the shape:
```json
{
"agents": {
"busy": 0,
"idle": 0,
"total": 0
},
"jobs": {
"running": 0,
"scheduled": 0,
"total": 0,
"waiting": 0
},
"organization": {
"slug": "buildkite"
}
}
```
=> Use the metrics route scoped to a queue to get metrics for the queue

CHANGELOG.md, version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-scaler/compare/v1.5.0...v1.5.1)
- A new release process which will fix publish releases to S3 [#97](https://github.com/buildkite/buildkite-agent-scaler/pull/97) (@triarius)
=> Update version and CHANGELOG for v1.5.1

.buildkite/steps/upload-to-s3.sh
The $BUILDKITE_TAG should have the `v`, the metadata does not. But just
in case, we remove the `v` and add it back.
=> Fix scaler release does not prepend a v to the version on s3

template.yaml
The rate expression must pluralise the unit, so `1 minute` and `0 minutes` are valid, but `0 minute` is not.
Rather than condition on the value of the parameter, we leave this to
the user to specify whether they should use "minute" or "minutes". This
also allows them to use other units like 1 hour, 1 day, etc. Though
units that are longer or shorter than a minute are not recommended.
Since the old parameter was essentially broken (it would not succeed with any value other than the default, `1`), we've decided to rename the parameter to `EventSchedulePeriod`. This name is more accurate - a length of time like 1 minute is not a rate.
=> Change `EventScheduleRate` parameter to `EventSchedulePeriod` and require units

Makefile, template.yaml
The go1.x runtime is being deprecated in favour of the provided.al2 runtime, see [this post](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/) for background.
We implemented the steps in the blog post the following PR https://github.com/buildkite/buildkite-agent-scaler/pull/103 however, at the time the library AWS-Lambda-Go was at an old version that was incompatible with the provided.al2 runtime. After the runtime was upgraded in https://github.com/buildkite/buildkite-agent-scaler/pull/107 the changes in this PR should make the scaler work with provided.al2 lambda runtime.
=> AWS Lambda end of support for the Go 1.x runtime

CHANGELOG.md, version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-scaler/compare/v1.6.0...v1.7.0)
- AWS Lambda end of support for the Go 1.x runtime [#108](https://github.com/buildkite/buildkite-agent-scaler/pull/108) (@HugeIRL)
- Bump github.com/aws/aws-sdk-go 1.45.25 [#109](https://github.com/buildkite/buildkite-agent-scaler/pull/109) [#106](https://github.com/buildkite/buildkite-agent-scaler/pull/106) (@dependabot[bot])
- Bump github.com/aws/aws-lambda-go from 1.7.0 to 1.41.0 [#107](https://github.com/buildkite/buildkite-agent-scaler/pull/107) (@dependabot[bot])
- Add dependabot [#105](https://github.com/buildkite/buildkite-agent-scaler/pull/105) (@triarius)
=> Update version and CHANGELOG for v1.7.0

README.md
README example needs updated to show new runtime to be used rather than one to be made deprecated
=> Update README example due to end of support for the Go 1.x runtime

.github/dependabot.yml
We added dependabot in #105 (Oct 2023) and it got very excited proposing daily updates to github.com/aws/aws-sdk-go. 
Eventually it gave up.
Maybe monthly is enough to stop dependencies falling behind, without quite so much noise?
=> Calm dependabot down a little

.buildkite/pipeline.yaml, .buildkite/steps/tests.sh, Makefile, go.mod, go.sum, lambda/env.go, lambda/main.go, scaler/scaler.go
This is a grab-bag of code cleanups.
The only significant change should be that `scaler.Run` now happens before checking `timeout`, so the lambda won't time out before it does anything useful (regardless of `LAMBDA_TIMEOUT`).
=> Scaler cleanups

CHANGELOG.md, version/version.go
[Full Changelog](https://github.com/buildkite/buildkite-agent-scaler/compare/v1.7.0...v1.8.0)
- The scaler will run at least once, regardless of `LAMBDA_TIMEOUT` [#188](https://github.com/buildkite/buildkite-agent-scaler/pull/188) (@DrJosh9000)
- Dependabot updates [#185](https://github.com/buildkite/buildkite-agent-scaler/pull/185), [#186](https://github.com/buildkite/buildkite-agent-scaler/pull/186), [#114](https://github.com/buildkite/buildkite-agent-scaler/pull/114) (@dependabot[bot])
- Fix dependabot reviewers [#187](https://github.com/buildkite/buildkite-agent-scaler/pull/187) (@DrJosh9000)
- Added Using Cluster [#183](https://github.com/buildkite/buildkite-agent-scaler/pull/183) (@stephanieatte)
- Calm dependabot down a little …
=> Bump changelog and version for v1.8.0

.buildkite/pipeline-sar.yaml
The update to Go 1.22 broke this extra pipeline, but it should be an easy fix.
=> Update Go to 1.22 in the SAR pipeline

template.yaml
We are currently trying to configure restrictions on the agent token by IP address, re: https://buildkite.com/docs/clusters/manage-clusters#restrict-an-agent-tokens-access-by-ip-address
In order to do this, we need the ability to configure the Lambda to run within dedicated subnet(s). This PR enables this, while not changing the behavior by default for others. I've tested this and not suppyling the new security group and subnet values, results in a non-VPC-associated Lambda. 
Note: We are not using the Elastic CI stack. Our use case required us to deploy this Lambda via https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/serverlessapplicationrepository_cloudformation_stack . With that in mind, we likely wouldn't be pursuing a followup PR to enable this for users of …
=> Enable subnet and security group configuration in Cloudformation

.buildkite/pipeline-sar.yaml
The new roel has the same permissions, only the name has changed
=> Update the role used to publish SAR

.buildkite/pipeline.yaml, .buildkite/steps/upload-to-s3.sh
We recently moved the S3 buckets that host our public lambdas to a new AWS account, and the OIDC assumable IAM roles for publishing to the buckets moved with them.
The replacement buckets have the same name, so we don't need to change them. However the recreated buckets use BucketOwnerEnforced for ownership and resource policies for access, instead of ACLs. We need to remove `--acl` from the upload command.
=> Update release process to assume new IAM roles via OIDC

.buildkite/pipeline-sar.yaml
This is our preferred pattern for interacting with AWS in pipelines, rather than relying on the instance role.
=> Assume an IAM role for publishing to SAR S3 bucket

buildkite/buildkite.go, buildkite/buildkite_test.go, lambda/env.go, lambda/main.go, main.go, template.yaml
I have this new endpoint in a way that always defaults to https://agent.buildkite.com/v3 if not provided to ensure compability with old installations or forks.
I used `AgentEndpoint` for the param name in the template as it matches the name in the elastic stack template.
=> Add an option to override the agent endpoint URL via flag and env var

template.yaml
Fix IAM role used by the agent-scaler in ElasticCIMode (introduced in https://github.com/buildkite/buildkite-agent-scaler/pull/212), so it can send SIGTERM (graceful scale-in), and terminate Elastic Stack's EC2 instances when dangling instances detected.
Verified with my own stack just now.
=> fix: correct permissions to handle instances in ElasticCIMode

template.yaml
As per [https://docs.aws.amazon.com/systems-manager/latest/userguide/run-command-setting-up.html#tag-based-access](https://docs.aws.amazon.com/systems-manager/latest/userguide/run-command-setting-up.html#tag-based-access), we need two statements to restrict SSM command runs.
1. `ssm:SendCommand` and `ssm:GetCommandInvocation` are now conditional on target EC2 instances possessing **both**:    
- `Role: buildkite-agent` tag
- `aws:autoscaling:groupName` tag matching the `!Ref AgentAutoScaleGroup` parameter passed down from the Elastic CI Stack CloudFormation Stack
2. `ec2:TerminateInstances` is now conditional on target EC2 instances possessing **both**:
- `Role: buildkite-agent`
- `aws:autoscaling:groupName` tag matching the `!Ref AgentAutoScaleGroup` parameter passed down from the …
=> fix: scope down ElasticCIModeSSMAndEC2 policy

template.yaml
- A scaler function event schedule runs on a cron, so having 30 seconds is an invalid option and should be removed from the examples; the minimum value that can be set is `1 minute`, which is already the default
=> fix: event schedule examples
